name: build01
on:
  schedule:
    - cron: '30 12 8 12 *'

jobs:
  build01:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git checkout & merge
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout main
          git merge test
          git tag 20211208.01
          git checkout 20211208.01
          git push origin main
      - name: hello
        run: |
          echo "hello world!1"